## docker-compose.yml
## author: Borgia Leiva (@a-mayb3) <edoardo.borgia.leiva@outlook.com>

services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=group_n_meet
    volumes:
      - ./.postgresql/.postgres-data:/var/lib/postgresql/

  fastapi:
    build:
      context: ./backend
      dockerfile: dockerfile
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=group_n_meet
      - SESSION_SECRET_KEY=${SESSION_SECRET_KEY}
      - BIND_ADDRESS=0.0.0.0
    depends_on:
      - postgres
    develop:
      watch:
        - action: rebuild
          path: ./backend

  frontend:
    build:
      context: ./angular
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "80"
    develop:
      watch:
        - action: rebuild
          path: ./angular

  nginx:
    image: nginx:alpine
    ports:
      - "0.0.0.0:80:80"
    depends_on:
      frontend:
        condition: service_started
      fastapi:
        condition: service_healthy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    develop:
      watch:
        - action: rebuild
          path: ./nginx